<?php
ini_set("error_reporting", 1);
session_start();
//require_once "waktu.php";
include"koneksi.php";

?>
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Dyeing | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="plugins/iCheck/square/blue.css">
    <!--alerts CSS -->
    <link href="bower_components/sweetalert/sweetalert2.css" rel="stylesheet" type="text/css">


    <style>
      body{
		font-family: Calibri, "sans-serif", "Courier New";  /* "Calibri Light","serif" */
		font-style: normal;
	}
	  .headline {
  color: #fff;
  text-shadow: 1px 3px 5px rgba(0, 0, 0, 0.5);
  font-weight: 300;
  -webkit-font-smoothing: antialiased !important;
  opacity: 0.8;
  margin: 0px 0 0px 0;
  font-size: 60px;
}
</style>
    <link rel="icon" type="image/png" href="dist/img/ITTI_Logo index.ico">
  </head>

  <body class="hold-transition login-page">
    <div class="login-box">
      <div class="login-logo">
		<a href="index.php"><b>DYE</b> ITTI</a>  
        <img src="dist/img/ITTI_LogoShape.png" class="user-image" alt="User Image">
      </div>
      <!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="" method="post">
          <div class="form-group has-feedback">
            <input type="text" class="form-control" placeholder="UserName" name="username">
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" placeholder="Password" name="password">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">
              <!-- <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div> -->
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div>
            <!-- /.col -->

          </div>
        </form>

        <!-- <div class="social-auth-links text-center">
      <p>- OR -</p>
      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
        Facebook</a>
      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
        Google+</a>
    </div> -->
        <!-- /.social-auth-links -->

        <!-- <a href="#">I forgot my password</a><br>
    <a href="register.html" class="text-center">Register a new membership</a> -->

      </div>
      <!-- /.login-box-body -->

      <div class="headline text-center" id="time">
        <!-- Time auto generated by js -->
      </div>
    </div>
    <!-- /.login-box -->

    <!-- jQuery 3 -->
    <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="plugins/iCheck/icheck.min.js"></script>
    <!-- Sweet Alert -->
    <script type="text/javascript" src="bower_components/sweetalert/sweetalert2.min.js"></script>
    <script>
      $(function() {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });

    </script>
    <!-- page script -->
    <script type="text/javascript">
      $(function() {
        startTime();
        $(".center").center();
        $(window).resize(function() {
          $(".center").center();
        });
      });

      /*  */
      function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();

        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);

        //Check for PM and AM
        var day_or_night = (h > 11) ? "PM" : "AM";

        //Convert to 12 hours system
        if (h > 12)
          h -= 12;

        //Add time to the headline and update every 500 milliseconds
        $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
        setTimeout(function() {
          startTime()
        }, 500);
      }

      function checkTime(i) {
        if (i < 10) {
          i = "0" + i;
        }
        return i;
      }

      /* CENTER ELEMENTS IN THE SCREEN */
      jQuery.fn.center = function() {
        this.css("position", "absolute");
        this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
          $(window).scrollTop()) - 30 + "px");
        this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
          $(window).scrollLeft()) + "px");
        return this;
      }

    </script>
  </body>

</html>
<?php
if ($_POST) { //login user
    extract($_POST);
    $username = mysqli_real_escape_string($con,$_POST['username']);
    $password = mysqli_real_escape_string($con,$_POST['password']);
    $sql=mysqli_query($con,"select * from tbl_user where username='$username' and password='$password' and (dept='DYE' or dept='DIT') limit 1");
    if (mysqli_num_rows($sql)>0) {
        $_SESSION['user_id10']=$username;
        $_SESSION['pass_id10']=$password;
        $r = mysqli_fetch_array($sql);
		$_SESSION['id10']=$r['id'];
		$_SESSION['nama10']=$r['nama'];
        $_SESSION['lvl_id10']=$r['level'];
        $_SESSION['status10']=$r['status'];
        $_SESSION['foto10']=$r['foto'];
        //login_validate();
        //echo "<script>window.location='index1.php?p=Home';</script>";
        echo "<script>swal({
  title: 'Login Sukses!!',
  text: 'Klik Ok untuk melanjutkan',
  type: 'success',
  }).then((result) => {
  if (result.value) {
    window.location='index1.php?p=Home';
  }
});</script>";
    /*echo "<script> swal({
            title: 'Login Sukses!!',
            text: ' Klik Ok untuk melanjutkan',
            type: 'success'
        }, function(){
            window.location='index1.php?p=Home';
        });</script>";*/
    } else { // echo "<script>alert('Login Gagal!! $username');window.location='index.php';</script>";
        echo "<script> swal({
            title: 'Login Gagal!!',
            text: ' Klik Ok untuk Login kembali',
            type: 'warning'
        }, function(){
            window.location='login';
        });</script>";
    }
} elseif ($_GET['act']=="logout") { //logout user
    unset($_SESSION['user_id10']);
    echo "<script>window.location='login';</script>";
}
?>
